{% set name = "rb-fsevent" %}
{% set version = "0.11.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: d585e0211cacbb793b4444e911212b3733f7dfb1c3016cb6c5fcacd8f7058519

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: http://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: FSEvents API with Signals catching (without RubyCocoa)

  dev_url: https://github.com/thibaudgg/rb-fsevent

extra:
  recipe-maintainers:
    - sodre
