travis:
  secure:
    BINSTAR_TOKEN: dazLJ2Uly8XMUPj7oPSRkqild7xvKlNgn39oB3Go3qLuX38gksLZ26eCrU9nGNZMdI3DDZhAjjWAwrm79dzPtU4TMm0KYzSIZW6B1w9V05rgGpkscHFq6WyUrdck1Mnw6I1hRrEaEJkNTDge6T3ANVsSQXcWQHGM1rIh8ewUdya1vBcQNiWCEhH+D+pHJbmNx4ujskpCJlNQ4hhszlgWB1ibelcOwqi5ZG4Q2a6fpjkWzgPHuo4oJcroLUGbYwzy7Jdka9fcnFOILm5ri+qwr97+LCdD9kJBmb0R8e/V8rm9PuH1k6CKQDbVpodQQE+EtdgRobnoII5TCv2lHYxWyFOeIzXfGNPErl5QdlESgIIfpiS8+7thaCrqjlhzAy9G1poxVzRU8T1mYAJSGEByQ8cCCcJMwFehjkQBUQnCz+g28jIaViOqSnnMbzic4vGCZ5CyX1bcr9DU4HuEIwtpQ0Kzve97Og/ectl1YUhofxy1/DC4li22X6GQL7JhB8Ade/1KtzDvJSf/W9cEt3gEY6HIQLowTr1CSeWPjoy1hSyRqO8RBBDEgi/AYS4QGh4xUPkbBPseG7+bMrEyYCAu+aSKuQS/DmytKe84FgH8pPXwpbqUP0qiCNJ162s3CmjQOuFXWDWPILsiLQYl2vC2pixOBexuuDh1WZiks0Ql66o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
